### ISSUE TITLE
ending slash breaks it

### ISSUE THREAD

**Issue by danito** [egoexpress/known-shortprofile#1]
I had to remove the ending / from https://instagram.com/nxd4n/ as the instagram icon was shown without the username.

Maybe add a $url = rtrim($url, '/'); in https://github.com/egoexpress/known-shortprofile/blob/master/templates/default/shortprofile/fields.tpl.php#L8

**Comment by egoexpress** [comment]
You're right. Thanks for the suggestion, I'll fix that.

**Comment by danito** [comment]
for my G+ account I put https://plus.google.com/+DanielNix/about ...
...I know ;-)
