### ISSUE TITLE
Icon's not showing in Known 0.9.9-a

### ISSUE THREAD

**Issue by davidmead** [egoexpress/known-shortprofile#4]
I tried this with the 0.9.9 build, that's available on http://withknown.com, and it worked great.

To fix issues with Known itself I updated to 0.9.9-a, from @mapkyca's [Known site](https://www.marcus-povey.co.uk/known/), but now it no longer displays a lot of the icons.

![screen shot 2019-01-02 at 8 30 01 pm](https://user-images.githubusercontent.com/1266930/50728102-c3864f00-10f2-11e9-9357-7be248099209.png)

Any ideas?

**Comment by mapkyca** [comment]
Custom theme?

Fontawesome was upgraded in recent versions, so check that was upgrade correctly, and the css is referenced properly. A ctrl-f5 might not hurt either.

**Comment by davidmead** [comment]
Default theme.

I chose another theme last night, just in case, and it's the same. Cleared cache and did cmd+r for refresh.

No changes. Is there a link/file to fontawesome somewhere in the code I should be looking for then?

**Comment by mapkyca** [comment]
Ahh wait, just noticed this wasn't a ticket on core. 

Look like the plugin replaces the profile template and so needs to be updated with the new fontawesome class names.

**Comment by davidmead** [comment]
I'll try to fork and fix it.

**Comment by egoexpress** [comment]
Looking forward to the PR.
