### ISSUE TITLE
Merge with fork-awesome changes

### ISSUE THREAD

**Issue by lindner** [egoexpress/known-shortprofile#6]
The link template code changed in Known a while back to use fork-awesome instead of fontawesome.

Would be interested in seeing this plugin merge that in some how.  Or perhaps just push this upstream?

**Comment by absolonkent** [comment]
I was interested in looking into it, but I haven't had time for side projects lately. I think I updated the code on my personal site, but never updated the package here.

**Comment by egoexpress** [comment]
I'll have a look into this. So you mean the references to the Font Awesome icons have to be changed to use Fork Awesome instead?

**Comment by lindner** [comment]
Yeah, we moved to fork awesome a while back since it had more glyphs for
more services.

Might also make sense to merge this into main along with a setting to
control it, but it also serves as a useful example of how you can customize
templates...

**Comment by egoexpress** [comment]
I just changed the template to use the Fork Awesome icons. Periscope and Ello got lost on the way as there is no matching icon in Fork Awesome - I tried to find the closest match.
